controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    base_to_mid_joint_position_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    mid_to_top_joint_position_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"


base_to_mid_joint_position_controller:
  ros__parameters:
    joints:
      - base_to_mid_joint   
    command_interfaces:
      - position
    state_interfaces:
      - position
      
     
mid_to_top_joint_position_controller:
  ros__parameters:
    joints:
      - mid_to_top_joint   
    command_interfaces:
      - position
    state_interfaces:
      - position



           


